<?php get_header( 'demo' );

global $post;
$post_slug      = $post->post_name;
$blog_detail    = get_blog_details( get_current_blog_id() );
$childtheme_uri = str_replace( 'tdm/', '', get_stylesheet_directory_uri() );


?>

    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="<?php echo $childtheme_uri . '/assets/images/' . $post_slug . '_tdm.jpg'; ?>"
         usemap="#image-map">

    <map name="image-map">
        <area target="_self" alt="Room &amp; Suites" title="Room &amp; Suites" href="#roomandsuites"
              coords="629,92,446,53" shape="rect">
        <area target="_self" alt="Deal &amp; Packages" title="Deal &amp; Packages" href="#deal&amp;packages"
              coords="642,52,844,90" shape="rect">
        <area target="_self" alt="Dining" title="Dining" href="#dining" coords="856,55,948,92" shape="rect">
        <area target="_self" alt="Experience" title="Experience" href="#experiences" coords="960,57,1095,84"
              shape="rect">
        <area target="_self" alt="Events" title="Events" href="#events" coords="1104,53,1200,87" shape="rect">
        <area target="_self" alt="Photos" title="Photos" href="#photo" coords="1217,56,1311,84" shape="rect">
        <area target="_self" alt="New &amp; blog" title="New &amp; blog" href="#newandblog" coords="1321,52,1472,86"
              shape="rect">
        <area target="_self" alt="Room detail" title="Room detail" href="#roomdetail" coords="308,446,1302,2366"
              shape="rect">
    </map>


<?php get_footer( 'demo' ); ?>