<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - HOTEL DEVELOPMENT</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/hotel-development.jpg'); ?>" usemap="#image-map" width="100% ">

	<map name="image-map">
		<area target="" alt="BH Logo Header" title="BH Logo Header" href="<?php echo home_url( '/' ); ?>" coords="30,10,229,149" shape="0">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="322,51,475,101" shape="rect">
	    <area target="" alt="Coporate Governance" title="Coporate Governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="489,49,759,99" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';" coords="773,53,843,95" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="853,53,964,95" shape="0">
	    <area target="" alt="Hotel Development" title="Hotel Development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="978,53,1208,95" shape="0">
	    <area target="" alt="Explore BD" title="Explore BD" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1223,51,1453,95,1413,69" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1469,53,1596,93" shape="0">
	    <area target="" alt="" title="" href="" coords="849,3418,1075,3538" shape="0">
	    <area target="" alt="" title="" href="" coords="676,3546,825,3649" shape="0">
	    <area target="" alt="" title="" href="" coords="839,3550,978,3649" shape="0">
	    <area target="" alt="" title="" href="" coords="984,3552,1139,3651" shape="0">
	    <area target="" alt="" title="" href="" coords="1147,3550,1260,3659" shape="0">
	    <area target="" alt="" title="" href="" coords="366,3707,557,3770" shape="0">
	    <area target="" alt="" title="" href="" coords="610,3709,853,3760" shape="0">
	    <area target="" alt="" title="" href="" coords="900,3711,1202,3756" shape="0">
	    <area target="" alt="" title="" href="" coords="1260,3715,1590,3760" shape="0">
	    <area target="" alt="" title="" href="" coords="785,3908,1145,3975" shape="0">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
