<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - PROPERTIES</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/properties.jpg'); ?>" usemap="#image-map" width="100%">
	<map name="image-map">
	    <area target="" alt="BH Logo" title="BH Logo" href="<?php echo home_url( '/' ); ?>" coords="203,145,24,20" shape="rect">
	    <area target="" alt="" title="properties" href="<?php echo home_url( '/properties' ); ?>" coords="318,55,465,103" shape="0">
	    <area target="" alt="" title="coporate governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="485,55,755,107" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';"  coords="767,59,849,97" shape="0">
	    <area target="" alt="" title="careers" href="<?php echo home_url( '/careers' ); ?>" coords="861,57,968,105" shape="0">
	    <area target="" alt="" title="hotel development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="976,59,1210,105" shape="0">
	    <area target="" alt="" title="explore binh duong" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1220,61,1453,101" shape="0">
	    <area target="" alt="" title="wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1467,61,1596,97" shape="0">
	    <area target="" alt="" title="info NC" href="" coords="296,972,632,1032" shape="0">
	    <area target="" alt="" title="find now NC" href="<?php echo home_url( '/newcity' ); ?>" coords="292,1197,451,1257" shape="0">
	    <area target="" alt="" title="info TDM" href="" coords="970,1543,1348,1601" shape="0">
	    <area target="" alt="" title="find now TDM" href="<?php echo home_url( '/tdm' ); ?>" coords="968,1768,1125,1831" shape="0">
	    <area target="" alt="" title="map" href="" coords="28,2094,1914,2613" shape="0">
	    <area target="" alt="" title="logo BH footer" href="<?php echo home_url( '/' ); ?>" coords="857,2776,1061,2880" shape="0">
	    <area target="" alt="" title="NC Logo" href="<?php echo home_url( '/newcity' ); ?>" coords="678,2890,819,3007" shape="0">
	    <area target="" alt="" title="TDM Logo" href="<?php echo home_url( '/tdm' ); ?>" coords="835,2898,968,2999" shape="0">
	    <area target="" alt="" title="Coffee Logo" href="" coords="984,2901,1137,3001" shape="0">
	    <area target="" alt="" title="Square Logo" href="" coords="1143,2896,1240,3007" shape="0">
	    <area target="" alt="" title="Info 1" href="" coords="362,3053,561,3104" shape="0">
	    <area target="" alt="" title="Info 2" href="" coords="614,3063,847,3102" shape="0">
	    <area target="" alt="" title="INfo 3" href="" coords="902,3061,1212,3106" shape="0">
	    <area target="" alt="" title="Info 4" href="" coords="1248,3061,1610,3106" shape="0">
	    <area target="" alt="" title="" href="Social" coords="793,3252,1167,3321" shape="0">
	    <area target="" alt="" title="" href="#" coords="1829,3089,1908,3168" shape="0">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
