<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - NEWS</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/news.jpg'); ?>" usemap="#image-map" width="100%">

	<map name="image-map">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="310,51,463,101" shape="rect">
	    <area target="" alt="Coporate Governance" title="Coporate Governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="467,49,737,99" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';" coords="745,53,815,95" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="819,51,930,93" shape="0">
	    <area target="" alt="Hotel Development" title="Hotel Development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="940,53,1159,97" shape="0">
	    <area target="" alt="Explore BD" title="Explore BD" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1171,53,1401,97,1361,71" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1415,53,1528,95" shape="0">
	    <area target="" alt="BH Logo Header" title="BH Logo Header" href="<?php echo home_url( '/' ); ?>" coords="22,14,221,153" shape="0">
	    <area target="" alt="Title 1" title="Title 1" href="<?php echo home_url( '/news-single' ); ?>" coords="135,1469,938,1600" shape="0">
	    <area target="" alt="Detail 1" title="Detail 1" href="<?php echo home_url( '/news-single' ); ?>" coords="137,1722,248,1758" shape="0">
	    <area target="" alt="Title 2" title="Title 2" href="<?php echo home_url( '/news-single' ); ?>" coords="974,1479,1781,1600" shape="0">
	    <area target="" alt="Detail 2" title="Detail 2" href="<?php echo home_url( '/news-single' ); ?>" coords="976,1722,1077,1758" shape="0">
	    <area target="" alt="Title 3" title="Title 3" href="<?php echo home_url( '/news-single' ); ?>" coords="137,2485,940,2605" shape="0">
	    <area target="" alt="Detail 3" title="Detail 3" href="<?php echo home_url( '/news-single' ); ?>" coords="139,2726,246,2766" shape="0">
	    <area target="" alt="Title 4" title="Title 4" href="<?php echo home_url( '/news-single' ); ?>" coords="978,2481,1783,2599" shape="0">
	    <area target="" alt="Detail 4" title="Detail 4" href="<?php echo home_url( '/news-single' ); ?>" coords="974,2726,1093,2762" shape="0">
	    <area target="" alt="BH Logo footer" title="BH Logo footer" href="<?php echo home_url( '/' ); ?>" coords="853,3022,1069,3132" shape="0">
	    <area target="" alt="Logo NC" title="Logo NC" href="" coords="682,3146,823,3245" shape="0">
	    <area target="" alt="Logo TDM" title="Logo TDM" href="" coords="833,3148,968,3245" shape="0">
	    <area target="" alt="Logo coffee" title="Logo coffee" href="" coords="978,3152,1143,3245" shape="0">
	    <area target="" alt="Logo Square" title="Logo Square" href="" coords="1147,3152,1246,3247" shape="0">
	    <area target="" alt="Info 1" title="Info 1" href="" coords="362,3305,551,3349" shape="0">
	    <area target="" alt="Info 2" title="Info 2" href="" coords="608,3305,843,3354" shape="0">
	    <area target="" alt="Info 3" title="Info 3" href="" coords="908,3313,1204,3356" shape="0">
	    <area target="" alt="Info 4" title="Info 4" href="" coords="1260,3319,1584,3356" shape="0">
	    <area target="" alt="Social" title="Social" href="" coords="803,3516,1141,3571" shape="0">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
