<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - COPERATE GOVERNANCE</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/coporate-governance.jpg'); ?>" usemap="#image-map" width="100%">

	<map name="image-map">
		<area target="" alt="Logo Becamex Header" title="Logo Becamex Header" href="<?php echo home_url( '/' ); ?>" coords="199,17,24,145" shape="0">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="310,51,463,101" shape="rect">
	    <area target="" alt="Coporate Governance" title="Coporate Governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="467,49,737,99" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';" coords="745,53,815,95" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="819,51,930,93" shape="0">
	    <area target="" alt="Hotel Development" title="Hotel Development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="940,53,1159,97" shape="0">
	    <area target="" alt="Explore BD" title="Explore BD" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1171,53,1401,97,1361,71" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1415,53,1528,95" shape="0">
	    <area target="" alt="BH Logo" title="BH Logo" href="<?php echo home_url( '/' ); ?>" coords="847,3676,1083,3782" shape="0">
	    <area target="" alt="NC Logo" title="NC Logo" href="" coords="688,3789,825,3911" shape="0">
	    <area target="" alt="TDM Logo" title="TDM Logo" href="" coords="833,3792,970,3908" shape="0">
	    <area target="" alt="Coffe Logo" title="Coffe Logo" href="" coords="984,3792,1137,3908" shape="0">
	    <area target="" alt="Square Logo" title="Square Logo" href="" coords="1147,3793,1256,3906,1226,3884" shape="0">
	    <area target="" alt="Info 1" title="Info 1" href="" coords="356,3948,551,4009" shape="0">
	    <area target="" alt="Info 2" title="Info 2" href="" coords="602,3962,851,4005" shape="0">
	    <area target="" alt="info 3" title="info 3" href="" coords="904,3962,1204,4007" shape="0">
	    <area target="" alt="Info 4" title="Info 4" href="" coords="1260,3964,1592,4005" shape="0">
	    <area target="" alt="Social" title="Social" href="" coords="785,4162,1155,4220" shape="0">
	    <area target="" alt="" title="Scroll up" href="#" coords="1830,3995,1902,4070" shape="rect">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
