<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - NEWS SINGLE</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/news-single.jpg'); ?>" usemap="#image-map" width="100%">

	<map name="image-map">
	    <area target="" alt="BH Logo" title="BH Logo" href="<?php echo home_url( '/' ); ?>" coords="8,9,219,133" shape="rect">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="320,41,459,101" shape="0">
	    <area target="" alt="Coporate Governance" title="Coporate Governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="467,39,736,103" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';" coords="746,43,819,99" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="827,45,931,97" shape="0">
	    <area target="" alt="Hotel development" title="Hotel development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="943,45,1163,95" shape="0">
	    <area target="" alt="Explore BD" title="Explore BD" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1175,43,1398,97" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1412,47,1541,97" shape="0">
	    <area target="" alt="Recent posts" title="Recent posts" href="" coords="1400,537,1833,913" shape="0">
	    <area target="" alt="Categories" title="Categories" href="" coords="1400,1011,1847,1401" shape="0">
	    <area target="" alt="Tags" title="Tags" href="" coords="1414,1630,1845,1753" shape="0">
	    <area target="" alt="Banner Sidebar" title="Banner Sidebar" href="" coords="1404,1799,1830,2056" shape="0">
	    <area target="" alt="Follow us" title="Follow us" href="" coords="1406,2157,1585,2201" shape="0">
	    <area target="" alt="Breadcrum" title="Breadcrum" href="<?php echo home_url( '/news' ); ?>" coords="219,155,290,189" shape="0">
	    <area target="" alt="Breadcrum home" title="Breadcrum home" href="<?php echo home_url( '/' ); ?>" coords="141,151,209,189" shape="0">
	    <area target="" alt="Share" title="Share" href="" coords="217,1773,324,1817" shape="0">
	    <area target="" alt="Author info" title="Author info" href="" coords="390,2079,507,2133" shape="0">
	    <area target="" alt="BH Logo footer" title="BH Logo footer" href="<?php echo home_url( '/' ); ?>" coords="860,3031,1049,3144" shape="0">
	    <area target="" alt="NC Logo" title="NC Logo" href="" coords="676,3154,817,3260" shape="0">
	    <area target="" alt="TDM Logo" title="TDM Logo" href="" coords="833,3156,974,3262" shape="0">
	    <area target="" alt="Coffe logo" title="Coffe logo" href="" coords="984,3162,1139,3260" shape="0">
	    <area target="" alt="Square logo" title="Square logo" href="" coords="1145,3162,1257,3260" shape="0">
	    <area target="" alt="info 1" title="info 1" href="" coords="362,3321,555,3361" shape="0">
	    <area target="" alt="info 2" title="info 2" href="" coords="601,3317,849,3357" shape="0">
	    <area target="" alt="info 3" title="info 3" href="" coords="915,3327,1205,3363" shape="0">
	    <area target="" alt="info 4" title="info 4" href="" coords="1261,3327,1589,3365" shape="0">
	    <area target="" alt="Social" title="Social" href="" coords="795,3526,1129,3574" shape="0">
	    <area target="" alt="Scroll up" title="Scroll up" href="#" coords="1824,3349,1899,3427" shape="0">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
