<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - NEWS SINGLE</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/news-2.jpg'); ?>" usemap="#image-map" width="100%">

	<map name="image-map">
	    <area target="" alt="BH Logo Header" title="BH Logo Header" href="<?php echo home_url( '/' ); ?>" coords="22,14,221,153" shape="0">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="310,51,463,101" shape="rect">
	    <area target="" alt="Coporate Governance" title="Coporate Governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="467,49,737,99" shape="0">
	    <area target="" alt="News" title="News" href="<?php echo home_url( '/news' ); ?>" coords="745,53,815,95" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="819,51,930,93" shape="0">
	    <area target="" alt="Hotel Development" title="Hotel Development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="940,53,1159,97" shape="0">
	    <area target="" alt="Explore BD" title="Explore BD" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1171,53,1401,97,1361,71" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1415,53,1528,95" shape="0">
	    <area target="" alt="Recent posts" title="Recent posts" href="<?php echo home_url( '/news-single' ); ?>" coords="1264,980,1648,1315" shape="0">
	    <area target="" alt="Categories" title="Categories" href="" coords="1268,1400,1638,1800" shape="0">
	    <area target="" alt="Instagram" title="Instagram" href="" coords="1268,1889,1616,2124" shape="0">
	    <area target="" alt="Tags" title="Tags" href="" coords="1270,2248,1622,2323" shape="0">
	    <area target="" alt="Sidebar Image" title="Sidebar Image" href="" coords="1620,2610,1262,2369" shape="0">
	    <area target="" alt="Follow us Sidebar" title="Follow us Sidebar" href="" coords="1264,2725,1439,2773" shape="0">
	    <area target="" alt="Title 1" title="Title 1" href="<?php echo home_url( '/news-single' ); ?>" coords="219,1464,1212,1599" shape="0">
	    <area target="" alt="Detail 1" title="Detail 1" href="<?php echo home_url( '/news-single' ); ?>" coords="223,1722,344,1762" shape="0">
	    <area target="" alt="Title 2" title="Title 2" href="<?php echo home_url( '/news-single' ); ?>" coords="221,2462,1083,2530" shape="0">
	    <area target="" alt="Detail 2" title="Detail 2" href="<?php echo home_url( '/news-single' ); ?>" coords="223,2741,332,2775" shape="0">
	    <area target="" alt="BH Logo footer" title="BH Logo footer" href="" coords="857,3057,1067,3165" shape="0">
	    <area target="" alt="NC logo" title="NC logo" href="<?php echo home_url( '/newcity' ); ?>" coords="682,3182,819,3282" shape="0">
	    <area target="" alt="TDM Logo" title="TDM Logo" href="<?php echo home_url( '/tdm' ); ?>" coords="835,3184,966,3284" shape="0">
	    <area target="" alt="Coffee logo" title="Coffee logo" href="" coords="978,3186,1131,3282" shape="0">
	    <area target="" alt="Square logo" title="Square logo" href="" coords="1143,3186,1250,3280" shape="0">
	    <area target="" alt="Info 1" title="Info 1" href="" coords="368,3338,565,3389" shape="0">
	    <area target="" alt="Info 2" title="Info 2" href="" coords="610,3338,859,3385" shape="0">
	    <area target="" alt="Info 3" title="Info 3" href="" coords="904,3342,1210,3387" shape="0">
	    <area target="" alt="Info 4" title="Info 4" href="" coords="1254,3344,1602,3389" shape="0">
	    <area target="" alt="" title="" href="" coords="791,3546,1147,3600" shape="0">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>