<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - CAREERS</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/careers.jpg'); ?>" usemap="#image-map" width="100%">

	<map name="image-map">
		<area target="" alt="Logo Becamex Header" title="Logo Becamex Header" href="<?php echo home_url( '/' ); ?>" coords="199,17,24,145" shape="0">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="322,51,471,103" shape="rect">
	    <area target="" alt="Coporate Gorvenance" title="Coporate Gorvenance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="481,51,759,103" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';" coords="767,55,847,99" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="855,55,962,103" shape="0">
	    <area target="" alt="Hotel development" title="Hotel development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="972,53,1212,101" shape="0">
	    <area target="" alt="Explore Binh Duong" title="Explore Binh Duong" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1224,53,1457,101" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1469,55,1590,99" shape="0">
	    <area target="" alt="View more header" title="View more header" href="" coords="873,429,1049,495" shape="0">
	    <area target="" alt="Apply Room Service" title="Apply Room Service" href="" coords="970,2602,1149,2681" shape="0">
	    <area target="" alt="Apply Chef" title="Apply Chef" href="" coords="169,3249,352,3330" shape="0">
	    <area target="" alt="Apply PT" title="Apply PT" href="" coords="970,3887,1153,3966" shape="0">
	    <area target="" alt="Logo Hospitality Footer" title="Logo Hospitality Footer" href="" coords="853,4364,1057,4484" shape="0">
	    <area target="" alt="Logo NC Footer" title="Logo NC Footer" href="<?php echo home_url( '/newcity' ); ?>" coords="684,4495,829,4601" shape="0">
	    <area target="" alt="Logo TDM Footer" title="Logo TDM Footer" href="<?php echo home_url( '/tdm' ); ?>" coords="833,4493,974,4601" shape="0">
	    <area target="" alt="Coffee Footer" title="Coffee Footer" href="" coords="980,4493,1139,4603" shape="0">
	    <area target="" alt="Square Footer" title="Square Footer" href="" coords="1145,4493,1254,4605" shape="0">
	    <area target="" alt="Info footer 1" title="Info footer 1" href="" coords="555,4704,376,4657" shape="0">
	    <area target="" alt="Info footer 2" title="Info footer 2" href="" coords="612,4663,849,4700" shape="0">
	    <area target="" alt="Info footer 3" title="Info footer 3" href="" coords="908,4665,1206,4698" shape="0">
	    <area target="" alt="Info footer 4" title="Info footer 4" href="" coords="1260,4667,1594,4702" shape="0">
	    <area target="" alt="Social Footer" title="Social Footer" href="" coords="801,4864,1131,4919" shape="0">
	    <area target="" alt="SCroll up" title="SCroll up" href="" coords="1827,3335,1908,3426" shape="rect">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
