<!DOCTYPE html>
<html>
<head>
	<title>Becamex Hospitality - WELLNESS</title>
</head>
<body>
	<!-- Image Map Generated by http://www.image-map.net/ -->
	<img src="<?php echo home_url('/wp-content/themes/iver-child/demo-layout/wellness.jpg'); ?>" usemap="#image-map" width="100%">

	<map name="image-map">
		<area target="" alt="BH Logo" title="BH Logo" href="<?php echo home_url( '/' ); ?>" coords="207,109,22,6" shape="0">
	    <area target="" alt="Properties" title="Properties" href="<?php echo home_url( '/properties' ); ?>" coords="318,27,471,77" shape="rect">
	    <area target="" alt="Coporate Governance" title="Coporate Governance" href="<?php echo home_url( '/coporate-governance' ); ?>" coords="485,25,755,75" shape="0">
	    <area target="_blank" alt="" title="news" href="<?php echo home_url( '/news-2' ); ?>" onclick="location.href='<?php echo home_url( '/news' ); ?>';" coords="771,27,841,69" shape="0">
	    <area target="" alt="Careers" title="Careers" href="<?php echo home_url( '/careers' ); ?>" coords="853,29,964,71" shape="0">
	    <area target="" alt="Hotel Development" title="Hotel Development" href="<?php echo home_url( '/hotel-development' ); ?>" coords="972,29,1202,71" shape="0">
	    <area target="" alt="Explore BD" title="Explore BD" href="<?php echo home_url( '/explore-binh-duong' ); ?>" coords="1219,27,1449,71,1409,45,1312,65" shape="0">
	    <area target="" alt="Wellness" title="Wellness" href="<?php echo home_url( '/wellness' ); ?>" coords="1465,31,1592,71" shape="0">
	    <area target="" alt="Gym Fitness" title="Gym Fitness" href="<?php echo home_url( '/gym-single' ); ?>" coords="16,719,1268,1415" shape="rect">
	    <area target="" alt="BH Logo Footer" title="BH Logo Footer" href="" coords="849,2212,1071,2316" shape="0">
	    <area target="" alt="NC Logo" title="NC Logo" href="" coords="682,2332,821,2435" shape="0">
	    <area target="" alt="TDM LOGo" title="TDM LOGo" href="" coords="835,2334,968,2435" shape="0">
	    <area target="" alt="Coffee Logo" title="Coffee Logo" href="" coords="982,2336,1131,2437" shape="0">
	    <area target="" alt="Square Logo" title="Square Logo" href="" coords="1143,2338,1244,2435" shape="0">
	    <area target="" alt="Info 1" title="Info 1" href="" coords="370,2491,559,2535" shape="0">
	    <area target="" alt="Info 2" title="Info 2" href="" coords="606,2497,855,2533" shape="0">
	    <area target="" alt="INfo 3" title="INfo 3" href="" coords="898,2499,1212,2545" shape="0">
	    <area target="" alt="Info 4" title="Info 4" href="" coords="1260,2501,1596,2539" shape="0">
	    <area target="" alt="Social" title="Social" href="" coords="801,2698,1135,2749" shape="0">
	    <area target="" alt="Scroll Up" title="Scroll Up" href="#" coords="1829,2533,1906,2598" shape="0">
	</map>
</body>
<script type="text/javascript" src="<?php echo home_url('/wp-content/themes/iver-child/js/imageMapResizer.min.js'); ?>"></script>
<script type="text/javascript">
	imageMapResize();
</script>
</html>
